using Microsoft.EntityFrameworkCore.SqlServer.Storage;

namespace Microsoft.EntityFrameworkCore.SqlServer.Test.Models.Migrations
{
    internal sealed class TypedArraySeedContext : MigrationContext<Patriarch>
    {
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            RemoveVariableModelAnnotations(modelBuilder);

            modelBuilder.Entity<Patriarch>().HasData(
                new Patriarch { Id = HierarchyId.GetRoot(), Name = "Eddard Stark" },
                new Patriarch { Id = HierarchyId.Parse("/1/"), Name = "Robb Stark" },
                new Patriarch { Id = HierarchyId.Parse("/2/"), Name = "Jon Snow" });
        }

        public override string GetExpectedMigrationCode(string migrationName, string rootNamespace)
        {
            return $@"using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;

namespace {rootNamespace}.Migrations
{{
    public partial class {migrationName} : Migration
    {{
        protected override void Up(MigrationBuilder migrationBuilder)
        {{
            migrationBuilder.CreateTable(
                name: ""{nameof(TestModels)}"",
                columns: table => new
                {{
                    {nameof(Patriarch.Id)} = table.Column<{nameof(HierarchyId)}>(type: ""hierarchyid"", nullable: false),
                    {nameof(Patriarch.Name)} = table.Column<string>(type: ""nvarchar(max)"", nullable: true)
                }},
                constraints: table =>
                {{
                    table.PrimaryKey(""PK_{nameof(TestModels)}"", x => x.{nameof(Patriarch.Id)});
                }});

            migrationBuilder.InsertData(
                table: ""{nameof(TestModels)}"",
                columns: new[] {{ ""{nameof(Patriarch.Id)}"", ""{nameof(Patriarch.Name)}"" }},
                values: new object[] {{ Microsoft.EntityFrameworkCore.HierarchyId.Parse(""/""), ""Eddard Stark"" }});

            migrationBuilder.InsertData(
                table: ""{nameof(TestModels)}"",
                columns: new[] {{ ""{nameof(Patriarch.Id)}"", ""{nameof(Patriarch.Name)}"" }},
                values: new object[] {{ Microsoft.EntityFrameworkCore.HierarchyId.Parse(""/1/""), ""Robb Stark"" }});

            migrationBuilder.InsertData(
                table: ""{nameof(TestModels)}"",
                columns: new[] {{ ""{nameof(Patriarch.Id)}"", ""{nameof(Patriarch.Name)}"" }},
                values: new object[] {{ Microsoft.EntityFrameworkCore.HierarchyId.Parse(""/2/""), ""Jon Snow"" }});
        }}

        protected override void Down(MigrationBuilder migrationBuilder)
        {{
            migrationBuilder.DropTable(
                name: ""{nameof(TestModels)}"");
        }}
    }}
}}
";
        }

        public override string GetExpectedSnapshotCode(string rootNamespace)
        {
            return $@"// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using {ThisType.Namespace};
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace {rootNamespace}.Migrations
{{
    [DbContext(typeof({ThisType.Name}))]
    partial class {ThisType.Name}ModelSnapshot : ModelSnapshot
    {{
        protected override void BuildModel(ModelBuilder modelBuilder)
        {{
#pragma warning disable 612, 618

            modelBuilder.Entity(""{ModelType.FullName}"", b =>
                {{
                    b.Property<{nameof(HierarchyId)}>(""{nameof(Patriarch.Id)}"")
                        .HasColumnType(""{SqlServerHierarchyIdTypeMappingSourcePlugin.SqlServerTypeName}"");

                    b.Property<string>(""{nameof(Patriarch.Name)}"")
                        .HasColumnType(""nvarchar(max)"");

                    b.HasKey(""{nameof(Patriarch.Id)}"");

                    b.ToTable(""{nameof(TestModels)}"");

                    b.HasData(
                        new
                        {{
                            {nameof(Patriarch.Id)} = Microsoft.EntityFrameworkCore.HierarchyId.Parse(""/""),
                            {nameof(Patriarch.Name)} = ""Eddard Stark""
                        }},
                        new
                        {{
                            {nameof(Patriarch.Id)} = Microsoft.EntityFrameworkCore.HierarchyId.Parse(""/1/""),
                            {nameof(Patriarch.Name)} = ""Robb Stark""
                        }},
                        new
                        {{
                            {nameof(Patriarch.Id)} = Microsoft.EntityFrameworkCore.HierarchyId.Parse(""/2/""),
                            {nameof(Patriarch.Name)} = ""Jon Snow""
                        }});
                }});
#pragma warning restore 612, 618
        }}
    }}
}}
";
        }
    }
}
