name: .NET

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set VERSION variable from branch
      run: echo "VERSION=$(echo $GITHUB_REF | cut -d'/' -f 4)" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Pack
      run: dotnet pack --configuration  Release --output ./bin /p:Version=${VERSION}
    - name: Push
      run: dotnet nuget push build/*${VERSION}.nupkg --source https://nuget.pkg.github.com/wearephenix --api-key ${{github.token}}
